# Generated by Django 5.0 on 2023-12-06 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=25)),
                ('last_name', models.CharField(max_length=25)),
                ('age', models.IntegerField(default=0)),
                ('phone', models.CharField(default='', max_length=25)),
                ('address', models.CharField(max_length=50)),
            ],
        ),
    ]
