# Generated by Django 5.0 on 2023-12-06 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tasks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_name', models.CharField(max_length=25)),
                ('number', models.CharField(max_length=25)),
                ('execute_time', models.IntegerField(default=0)),
            ],
        ),
    ]
